"""empty message

Revision ID: 0024852df905
Revises: 4f9d8f28d476
Create Date: 2021-06-09 08:59:23.339470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0024852df905'
down_revision = '4f9d8f28d476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wall_ibfk_1', 'wall', type_='foreignkey')
    op.create_foreign_key(None, 'wall', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wall', type_='foreignkey')
    op.create_foreign_key('wall_ibfk_1', 'wall', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
