"""empty message

Revision ID: 4f9d8f28d476
Revises: 0609b8017d5d
Create Date: 2021-06-09 08:57:43.319187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9d8f28d476'
down_revision = '0609b8017d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wall_ibfk_1', 'wall', type_='foreignkey')
    op.create_foreign_key(None, 'wall', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wall', type_='foreignkey')
    op.create_foreign_key('wall_ibfk_1', 'wall', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
