"""empty message

Revision ID: 573f5b7f03ad
Revises: bcd5ca3fc3f8
Create Date: 2021-06-09 09:03:05.569288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573f5b7f03ad'
down_revision = 'bcd5ca3fc3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_ibfk_3', 'comment', type_='foreignkey')
    op.drop_constraint('comment_ibfk_2', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('post_ibfk_2', 'post', type_='foreignkey')
    op.drop_constraint('post_ibfk_1', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post', 'wall', ['wall_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_ibfk_1', 'post', 'user', ['author_id'], ['id'])
    op.create_foreign_key('post_ibfk_2', 'post', 'wall', ['wall_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_2', 'comment', 'post', ['post_id'], ['id'])
    op.create_foreign_key('comment_ibfk_3', 'comment', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###
