"""empty message

Revision ID: 6a97a7d50690
Revises: 6d5fa22ebb06
Create Date: 2021-06-08 13:18:56.723718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a97a7d50690'
down_revision = '6d5fa22ebb06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wall_ibfk_1', 'wall', type_='foreignkey')
    op.create_foreign_key(None, 'wall', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wall', type_='foreignkey')
    op.create_foreign_key('wall_ibfk_1', 'wall', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
