"""empty message

Revision ID: 6d5fa22ebb06
Revises: 6ba413834cab
Create Date: 2021-06-06 21:09:03.178230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d5fa22ebb06'
down_revision = '6ba413834cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pic_id', sa.String(length=1000), nullable=True))
    op.drop_column('user', 'pic_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pic_id', mysql.VARCHAR(length=1000), nullable=True))
    op.drop_column('user', 'pic_id')
    # ### end Alembic commands ###
