"""empty message

Revision ID: d85b7db5cf3d
Revises: 573f5b7f03ad
Create Date: 2021-06-11 15:47:46.740456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85b7db5cf3d'
down_revision = '573f5b7f03ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('changes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'changes')
    # ### end Alembic commands ###
